release:
  branches:
  - 'main'
preset: 'conventionalcommits'
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
      changelogTitle: '# Changelog'
  - - '@semantic-release/github'
    - assets:
      - path: 'CHANGELOG.md'
        label: 'Changelog'
  - 'gradle-semantic-release-plugin'
  - - '@semantic-release/git'
    - assets:
      - 'CHANGELOG.md'
      - 'gradle.properties'
